---
- name: Install required dependencies
  ansible.builtin.apt:
    name:
      - gnupg
      - curl
    state: present
    update_cache: yes

- name: Download and add New Relic GPG Key
  ansible.builtin.shell: |
    curl -fsSL https://download.newrelic.com/infrastructure_agent/gpg/newrelic-infra.gpg | gpg --dearmor -o /usr/share/keyrings/newrelic-infra.gpg
  args:
    creates: /usr/share/keyrings/newrelic-infra.gpg

- name: Add New Relic APT Repository
  ansible.builtin.apt_repository:
    repo: "deb [signed-by=/usr/share/keyrings/newrelic-infra.gpg] https://download.newrelic.com/infrastructure_agent/linux/apt buster main"
    state: present
    filename: newrelic-infra

- name: Update APT Cache
  ansible.builtin.apt:
    update_cache: yes

- name: Install New Relic Infrastructure Agent
  ansible.builtin.package:
    name: newrelic-infra
    state: present

- name: Configure New Relic License Key
  ansible.builtin.copy:
    dest: /etc/newrelic-infra.yml
    content: |
      license_key: {{ newrelic_license_key }}
      custom_attribute:
        network: {{ network }}
        environment: {{ environment }}
      log_file: /var/log/newrelic-infra.log
    owner: root
    group: root
    mode: '0644'

- name: Start and Enable New Relic Service
  ansible.builtin.service:
    name: newrelic-infra
    state: started
    enabled: yes
